### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by teonbrooks**
Here are some docs update. For the EEG systems, how far in depth should we go about their explanation? same level of the MEG? currently, it's just pointing to the function

### CODE REVIEW

**Comment by dengemann** [comment]
youc just push (unless @agramfort did not give you push access)

**Comment by dengemann** [comment]
I'm building your docs, thanks Teon!

**Comment by teonbrooks** [comment]
ok, thanks @dengemann. so about the EEG section, what do we want to do about it? do you want me to explain on it?

**Comment by dengemann** [comment]
@teonlamont what do you have in mind? It's already pretty ok for a start, no?

**Comment by teonbrooks** [comment]
yeah, i think so too. anything else doc wise I should jump on?

**Comment by agramfort** [comment]
@teonlamont now you can push directly to my repo. Just don't rebase or
force push.

go go team !

**Comment by larsoner** [comment]
I am making a ton of changes right now... so don't edit yet :)

**Comment by agramfort** [comment]
I am fighting with my mail box...

**Comment by wmvanvliet** [comment]
And remember our motto: A feature doesn't exist if it isn't in the docs! (API reference doesn't count)

**Pull request merged**
